name: latest

on:
  release:
    types: [released]

jobs:
  update-latest:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: fetch images
        env:
          ARCH_IMAGE_REPO: dhiltgen/release
          FINAL_IMAGE_REPO: dhiltgen/ollama
          PUSH: "1"
        run: |
          export "VERSION=${GITHUB_REF_NAME#v}"
          env
          ./scripts/tag_latest.sh
